/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paulita
 */
import AppPackage.AnimationClass;
import com.opencsv.CSVReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;




public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    AnimationClass slide;
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
           
        slide = new AnimationClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPnlMenu = new javax.swing.JPanel();
        BotonUnaLinea = new rsbuttom.RSButtonMetro();
        BotonMultilinea = new rsbuttom.RSButtonMetro();
        BotonHome = new rsbuttom.RSButtonMetro();
        BotonTutoriales = new rsbuttom.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPFuncionalidad = new javax.swing.JPanel();
        jPBarraSup = new javax.swing.JPanel();
        BotonCerrar = new rsbuttom.RSButtonMetro();
        BotonMinim = new rsbuttom.RSButtonMetro();
        jButton1 = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelUnaLinea = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BotonImprimir = new rsbuttom.RSButtonMetro();
        jLabelUnaLinea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextUnaLinea = new javax.swing.JTextArea();
        jPanelMultilinea = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BotonImprimirMultilinea = new rsbuttom.RSButtonMetro();
        BotonBuscarCSV = new rsbuttom.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanelTutoriales = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlMenu.setBackground(new java.awt.Color(242, 101, 11));
        jPnlMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonUnaLinea.setBackground(new java.awt.Color(242, 101, 11));
        BotonUnaLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edicion.png"))); // NOI18N
        BotonUnaLinea.setColorHover(new java.awt.Color(242, 101, 11));
        BotonUnaLinea.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonUnaLinea.setColorPressed(new java.awt.Color(255, 153, 51));
        BotonUnaLinea.setFocusable(false);
        BotonUnaLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUnaLineaActionPerformed(evt);
            }
        });
        jPnlMenu.add(BotonUnaLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 65, 52));

        BotonMultilinea.setBackground(new java.awt.Color(242, 101, 11));
        BotonMultilinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/importarcsv.png"))); // NOI18N
        BotonMultilinea.setColorHover(new java.awt.Color(242, 101, 11));
        BotonMultilinea.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonMultilinea.setColorPressed(new java.awt.Color(255, 153, 51));
        BotonMultilinea.setFocusable(false);
        BotonMultilinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultilineaActionPerformed(evt);
            }
        });
        jPnlMenu.add(BotonMultilinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 65, 52));

        BotonHome.setBackground(new java.awt.Color(242, 101, 11));
        BotonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        BotonHome.setColorHover(new java.awt.Color(242, 101, 11));
        BotonHome.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonHome.setColorPressed(new java.awt.Color(255, 153, 51));
        BotonHome.setFocusable(false);
        BotonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHomeActionPerformed(evt);
            }
        });
        jPnlMenu.add(BotonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 65, 52));

        BotonTutoriales.setBackground(new java.awt.Color(242, 101, 11));
        BotonTutoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/videos.png"))); // NOI18N
        BotonTutoriales.setColorHover(new java.awt.Color(242, 101, 11));
        BotonTutoriales.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonTutoriales.setColorPressed(new java.awt.Color(255, 153, 51));
        BotonTutoriales.setFocusable(false);
        BotonTutoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTutorialesActionPerformed(evt);
            }
        });
        jPnlMenu.add(BotonTutoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 65, 52));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TUTORIALES");
        jPnlMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRINCIPAL");
        jPnlMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UNA LÍNEA");
        jPnlMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MULTILINEA");
        jPnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanel1.add(jPnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 490));

        jPFuncionalidad.setBackground(new java.awt.Color(255, 255, 255));
        jPFuncionalidad.setForeground(new java.awt.Color(102, 102, 102));
        jPFuncionalidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBarraSup.setBackground(new java.awt.Color(242, 101, 11));
        jPBarraSup.setForeground(new java.awt.Color(255, 255, 255));

        BotonCerrar.setBackground(new java.awt.Color(242, 101, 11));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        BotonCerrar.setColorHover(new java.awt.Color(242, 101, 11));
        BotonCerrar.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonCerrar.setColorPressed(new java.awt.Color(242, 101, 11));
        BotonCerrar.setFocusable(false);
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        BotonMinim.setBackground(new java.awt.Color(242, 101, 11));
        BotonMinim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/minimizar.png"))); // NOI18N
        BotonMinim.setColorHover(new java.awt.Color(242, 101, 11));
        BotonMinim.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonMinim.setColorPressed(new java.awt.Color(242, 101, 11));
        BotonMinim.setFocusable(false);
        BotonMinim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBarraSupLayout = new javax.swing.GroupLayout(jPBarraSup);
        jPBarraSup.setLayout(jPBarraSupLayout);
        jPBarraSupLayout.setHorizontalGroup(
            jPBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraSupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 802, Short.MAX_VALUE)
                .addComponent(BotonMinim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPBarraSupLayout.setVerticalGroup(
            jPBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraSupLayout.createSequentialGroup()
                .addGroup(jPBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotonMinim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPFuncionalidad.add(jPBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("#PANELPRINCIPAL");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jPFuncionalidad.add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 740, 470));

        jPanelUnaLinea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("#PANELUNALINEA");

        BotonImprimir.setBackground(new java.awt.Color(242, 101, 11));
        BotonImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir-blanco.png"))); // NOI18N
        BotonImprimir.setColorHover(new java.awt.Color(255, 153, 51));
        BotonImprimir.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonImprimir.setColorPressed(new java.awt.Color(255, 153, 51));
        BotonImprimir.setFocusable(false);
        BotonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImprimirActionPerformed(evt);
            }
        });

        jLabelUnaLinea.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelUnaLinea.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUnaLinea.setText("Ingrese el texto a imprimir:");

        jTextUnaLinea.setBackground(new java.awt.Color(255, 255, 255));
        jTextUnaLinea.setColumns(20);
        jTextUnaLinea.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextUnaLinea.setForeground(new java.awt.Color(102, 102, 102));
        jTextUnaLinea.setRows(4);
        jTextUnaLinea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextUnaLinea.setCaretColor(new java.awt.Color(102, 102, 102));
        jTextUnaLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextUnaLineaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextUnaLinea);

        javax.swing.GroupLayout jPanelUnaLineaLayout = new javax.swing.GroupLayout(jPanelUnaLinea);
        jPanelUnaLinea.setLayout(jPanelUnaLineaLayout);
        jPanelUnaLineaLayout.setHorizontalGroup(
            jPanelUnaLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUnaLineaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanelUnaLineaLayout.createSequentialGroup()
                .addGroup(jPanelUnaLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUnaLineaLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUnaLineaLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabelUnaLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(jPanelUnaLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUnaLineaLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );
        jPanelUnaLineaLayout.setVerticalGroup(
            jPanelUnaLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnaLineaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUnaLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(BotonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanelUnaLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUnaLineaLayout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );

        jPFuncionalidad.add(jPanelUnaLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 740, 470));

        jPanelMultilinea.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMultilinea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("#PANELMULTILINEA");
        jPanelMultilinea.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 34, 419, 88));

        BotonImprimirMultilinea.setBackground(new java.awt.Color(242, 101, 11));
        BotonImprimirMultilinea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonImprimirMultilinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir-blanco.png"))); // NOI18N
        BotonImprimirMultilinea.setColorHover(new java.awt.Color(255, 153, 51));
        BotonImprimirMultilinea.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonImprimirMultilinea.setColorPressed(new java.awt.Color(255, 153, 51));
        BotonImprimirMultilinea.setFocusable(false);
        BotonImprimirMultilinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImprimirMultilineaActionPerformed(evt);
            }
        });
        jPanelMultilinea.add(BotonImprimirMultilinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 351, 93, 88));

        BotonBuscarCSV.setBackground(new java.awt.Color(242, 101, 11));
        BotonBuscarCSV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonBuscarCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar-csv.png"))); // NOI18N
        BotonBuscarCSV.setColorHover(new java.awt.Color(255, 153, 51));
        BotonBuscarCSV.setColorNormal(new java.awt.Color(242, 101, 11));
        BotonBuscarCSV.setColorPressed(new java.awt.Color(255, 153, 51));
        BotonBuscarCSV.setFocusable(false);
        BotonBuscarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarCSVActionPerformed(evt);
            }
        });
        jPanelMultilinea.add(BotonBuscarCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 245, 93, 88));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanelMultilinea.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 470, 330));

        jPFuncionalidad.add(jPanelMultilinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 740, 470));

        jPanelTutoriales.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("#PANELTUTORIALES");

        javax.swing.GroupLayout jPanelTutorialesLayout = new javax.swing.GroupLayout(jPanelTutoriales);
        jPanelTutoriales.setLayout(jPanelTutorialesLayout);
        jPanelTutorialesLayout.setHorizontalGroup(
            jPanelTutorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTutorialesLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanelTutorialesLayout.setVerticalGroup(
            jPanelTutorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTutorialesLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jPFuncionalidad.add(jPanelTutoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 740, 470));

        jPanel1.add(jPFuncionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void BotonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHomeActionPerformed
        this.jPanelPrincipal.setVisible(true);
        this.jPanelMultilinea.setVisible(false);
        this.jPanelUnaLinea.setVisible(false);
        this.jPanelTutoriales.setVisible(false);
    }//GEN-LAST:event_BotonHomeActionPerformed

    private void BotonUnaLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUnaLineaActionPerformed
        this.jPanelUnaLinea.setVisible(true);
        this.jPanelMultilinea.setVisible(false);
        this.jPanelPrincipal.setVisible(false);
        this.jPanelTutoriales.setVisible(false);
    }//GEN-LAST:event_BotonUnaLineaActionPerformed

    private void BotonMultilineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultilineaActionPerformed
        this.jPanelMultilinea.setVisible(true);
        this.jPanelUnaLinea.setVisible(false);
        this.jPanelPrincipal.setVisible(false);
        this.jPanelTutoriales.setVisible(false);
    }//GEN-LAST:event_BotonMultilineaActionPerformed

    private void BotonMinimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimActionPerformed
        setExtendedState(this.CROSSHAIR_CURSOR); 
    }//GEN-LAST:event_BotonMinimActionPerformed

    private void BotonTutorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTutorialesActionPerformed
        this.jPanelTutoriales.setVisible(true);
        this.jPanelMultilinea.setVisible(false);
        this.jPanelUnaLinea.setVisible(false);
        this.jPanelPrincipal.setVisible(false);
    }//GEN-LAST:event_BotonTutorialesActionPerformed

    private void BotonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonImprimirActionPerformed

    private void jTextUnaLineaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUnaLineaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUnaLineaKeyTyped

    private void BotonImprimirMultilineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImprimirMultilineaActionPerformed
        
    }//GEN-LAST:event_BotonImprimirMultilineaActionPerformed

    private void BotonBuscarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarCSVActionPerformed
        abrirArchivoCSV();
    }//GEN-LAST:event_BotonBuscarCSVActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = this.jPnlMenu.getX();
        if (posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -125, 2, 2, jPnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-125, 0, 2, 2, jPnlMenu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro BotonBuscarCSV;
    private rsbuttom.RSButtonMetro BotonCerrar;
    private rsbuttom.RSButtonMetro BotonHome;
    private rsbuttom.RSButtonMetro BotonImprimir;
    private rsbuttom.RSButtonMetro BotonImprimirMultilinea;
    private rsbuttom.RSButtonMetro BotonMinim;
    private rsbuttom.RSButtonMetro BotonMultilinea;
    private rsbuttom.RSButtonMetro BotonTutoriales;
    private rsbuttom.RSButtonMetro BotonUnaLinea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelUnaLinea;
    private javax.swing.JPanel jPBarraSup;
    private javax.swing.JPanel jPFuncionalidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMultilinea;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTutoriales;
    private javax.swing.JPanel jPanelUnaLinea;
    private javax.swing.JPanel jPnlMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextUnaLinea;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private void abrirArchivoCSV() {
        JFileChooser fc=new JFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            abrirCSV(file.getAbsolutePath());
        } 

    }

    private void abrirCSV(String absolutePath) {
        DefaultTableModel mat=null;
                
        try {
            CSVReader csvReader = new CSVReader(new FileReader(absolutePath));
            String[] fila = null;
            int i=0;
            while((fila = csvReader.readNext()) != null) {
                if(i==0) mat=new DefaultTableModel(fila, 0);
                else mat.addRow(fila);
                System.out.println(fila[0]+ " | " + fila[1]+ " |  " + fila[2]);
                i++;
            }
            csvReader.close();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(mat!=null) tabla.setModel(mat);

            }
}
