/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robra.v2;

/**
 *
 * @author Paulita
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.rSButtonHome.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSButtonMenu = new rsbuttom.RSButtonMetro();
        rSButtonMenu1 = new rsbuttom.RSButtonMetro();
        rSButtonMenu2 = new rsbuttom.RSButtonMetro();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        rSButtonImportar = new rsbuttom.RSButtonMetro();
        rSButtonImpresion = new rsbuttom.RSButtonMetro();
        rSButtonTutoriales = new rsbuttom.RSButtonMetro();
        rSButtonHome = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        rSButtonMenu.setBackground(new java.awt.Color(0, 51, 255));
        rSButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu.png"))); // NOI18N
        rSButtonMenu.setColorHover(new java.awt.Color(0, 51, 255));
        rSButtonMenu.setColorNormal(new java.awt.Color(0, 51, 255));
        rSButtonMenu.setColorPressed(new java.awt.Color(0, 51, 255));
        rSButtonMenu.setFocusPainted(false);
        rSButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMenuActionPerformed(evt);
            }
        });

        rSButtonMenu1.setBackground(new java.awt.Color(0, 51, 255));
        rSButtonMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        rSButtonMenu1.setColorHover(new java.awt.Color(0, 51, 255));
        rSButtonMenu1.setColorNormal(new java.awt.Color(0, 51, 255));
        rSButtonMenu1.setColorPressed(new java.awt.Color(0, 51, 255));
        rSButtonMenu1.setFocusPainted(false);
        rSButtonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMenu1ActionPerformed(evt);
            }
        });

        rSButtonMenu2.setBackground(new java.awt.Color(0, 51, 255));
        rSButtonMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/minimizar.png"))); // NOI18N
        rSButtonMenu2.setColorHover(new java.awt.Color(0, 51, 255));
        rSButtonMenu2.setColorNormal(new java.awt.Color(0, 51, 255));
        rSButtonMenu2.setColorPressed(new java.awt.Color(0, 51, 255));
        rSButtonMenu2.setFocusPainted(false);
        rSButtonMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMenu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 758, Short.MAX_VALUE)
                .addComponent(rSButtonMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 757;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlMenu.setBackground(new java.awt.Color(214, 217, 223));
        pnlMenu.setForeground(new java.awt.Color(214, 217, 223));

        jPanel4.setBackground(new java.awt.Color(214, 217, 223));
        jPanel4.setForeground(new java.awt.Color(214, 217, 223));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("ROBRA V2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        rSButtonImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/importCSV.png"))); // NOI18N
        rSButtonImportar.setText("IMPORTAR ");
        rSButtonImportar.setColorBorde(null);
        rSButtonImportar.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonImportar.setColorNormal(new java.awt.Color(214, 217, 223));
        rSButtonImportar.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonImportar.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonImportar.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonImportar.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonImportar.setFocusPainted(false);
        rSButtonImportar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonImportar.setIconTextGap(20);
        rSButtonImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonImportarActionPerformed(evt);
            }
        });

        rSButtonImpresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit.png"))); // NOI18N
        rSButtonImpresion.setText("IMPRESION LINEA");
        rSButtonImpresion.setColorBorde(null);
        rSButtonImpresion.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonImpresion.setColorNormal(new java.awt.Color(214, 217, 223));
        rSButtonImpresion.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonImpresion.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonImpresion.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonImpresion.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonImpresion.setFocusPainted(false);
        rSButtonImpresion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonImpresion.setIconTextGap(20);
        rSButtonImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonImpresionActionPerformed(evt);
            }
        });

        rSButtonTutoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tutorial.png"))); // NOI18N
        rSButtonTutoriales.setText("TUTORIALES");
        rSButtonTutoriales.setColorBorde(null);
        rSButtonTutoriales.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonTutoriales.setColorNormal(new java.awt.Color(214, 217, 223));
        rSButtonTutoriales.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonTutoriales.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonTutoriales.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonTutoriales.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonTutoriales.setFocusPainted(false);
        rSButtonTutoriales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonTutoriales.setIconTextGap(20);
        rSButtonTutoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonTutorialesActionPerformed(evt);
            }
        });

        rSButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        rSButtonHome.setText("PRINCIPAL");
        rSButtonHome.setColorBorde(null);
        rSButtonHome.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonHome.setColorNormal(new java.awt.Color(214, 217, 223));
        rSButtonHome.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonHome.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonHome.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonHome.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonHome.setFocusPainted(false);
        rSButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHome.setIconTextGap(20);
        rSButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rSButtonImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonTutoriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rSButtonImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rSButtonImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rSButtonTutoriales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 142;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 690;
        gridBagConstraints.ipady = 540;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel5, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMenuActionPerformed
        int posicion = this.pnlMenu.getX();
        if (posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -210, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-210, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_rSButtonMenuActionPerformed

    private void rSButtonImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonImportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonImportarActionPerformed

    private void rSButtonImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonImpresionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonImpresionActionPerformed

    private void rSButtonTutorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonTutorialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonTutorialesActionPerformed

    private void rSButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHomeActionPerformed

    private void rSButtonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMenu1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonMenu1ActionPerformed

    private void rSButtonMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMenu2ActionPerformed
        //this.setExtendedState(ICONIFIED);
        //this.setExtendedState(1);
        setExtendedState(this.CROSSHAIR_CURSOR); 
    }//GEN-LAST:event_rSButtonMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnlMenu;
    private rsbuttom.RSButtonMetro rSButtonHome;
    private rsbuttom.RSButtonMetro rSButtonImportar;
    private rsbuttom.RSButtonMetro rSButtonImpresion;
    private rsbuttom.RSButtonMetro rSButtonMenu;
    private rsbuttom.RSButtonMetro rSButtonMenu1;
    private rsbuttom.RSButtonMetro rSButtonMenu2;
    private rsbuttom.RSButtonMetro rSButtonTutoriales;
    // End of variables declaration//GEN-END:variables
}
